CREATE TABLE IF NOT EXISTS trades (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `sellerID` INT UNSIGNED NOT NULL,
    `buyerID` INT UNSIGNED NOT NULL,
    `tokenID` INT UNSIGNED NOT NULL,
    `amount` DECIMAL(65, 0) NOT NULL,
    `price` DECIMAL(65, 0) NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sellerID) REFERENCES users(id),
    FOREIGN KEY (buyerID) REFERENCES users(id),
    FOREIGN KEY (tokenID) REFERENCES tokens(id)
);